# Generated by Django 4.2.4 on 2023-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente_estado_inventario_pedido_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='idCliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estado',
            name='idProducto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idCliente',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
